return {
    misc = {
        dictionary = {
            k_mcp_suit_up = "HANDS MUST CONTAIN ALL 4 SUITS",
        },
        v_text = {
            ch_c_mcp_no_refunds     = { "All sell values are set to {C:money}$0{}" },
            ch_c_mcp_black_market   = { "All shop prices are doubled" },
            ch_c_mcp_thrift_store   = { "Jokers and packs cost {C:attention}50%{} less" },
            ch_c_mcp_no_reroll      = { "The shop cannot be {C:attention}rerolled{}" },
            ch_c_mcp_impulse_buyer  = { "The first shop item buys itself if affordable" },
            ch_c_mcp_half_a_hand    = { "Can only select {C:attention}3{} cards at a time" },
            ch_c_mcp_slow_hands     = { "A big hand, but few to play. Play it slowly" },
            ch_c_mcp_suit_up        = { "Played hands must contain all 4 suits" },
            ch_c_mcp_one_trick      = { "Jokers you gain fill every slot with copies of itself. Selling one sells all copies" },
            ch_c_mcp_all_perishable = { "All Jokers are {C:eternal}Perishable{}" },
            ch_c_mcp_joker_draft    = { "Jokers are automatically sold for full value after each Boss Blind" },
            ch_c_mcp_poker_purist   = { "Each hand must beat the last played poker hand. {C:inactive}(Resets each round)" },
            ch_c_mcp_wild_west      = { "All cards except {C:attention}Wild{} cards are debuffed" },
            ch_c_mcp_balanstro      = { "Only your least played hand type may be played" },
            ch_c_mcp_double_down    = { "Jokers trigger twice. Blind sizes are doubled after Ante 1" },
            ch_c_mcp_final_form     = { "Gain {C:attention}+1{} Joker slot each Ante" },
            ch_c_mcp_recursion      = { "Scored cards are destroyed and replaced with random enhanced cards" },
            ch_c_mcp_glass_house    = { "Any hand that is not a {C:attention}Full House{} is destroyed" },
            ch_c_mcp_rusty_deck     = { "Steel cards are debuffed once played" },
            ch_c_mcp_tenant         = { "All Jokers are Rental. Income from blinds and hands is doubled" },
            ch_c_mcp_gambler        = { "First {C:attention}10{} rerolls are free, then {C:money}+$1{} each" },
            ch_c_mcp_gambler_risk   = { "Each reroll has a {C:green}1 in 6{} chance to destroy a Joker" },
            ch_c_mcp_long_game      = { "Must defeat Ante 16 to win" },
            ch_c_mcp_trial          = { "Every blind after Ante 1 is a Boss Blind" },
            ch_c_mcp_legendary_twist = { "{C:attention}Chicot{} is destroyed upon reaching {C:attention}Ante 8{}" },
            ch_c_mcp_homeless       = { "Start at {C:money}-$20{} with an {C:eternal}Eternal{} {C:attention}Vagabond{}" },
            ch_c_mcp_ivory_tower    = { "Only {C:attention}Jokers{} and {C:attention}Buffoon Packs{} appear. Start with {C:money}$20{}" },
            ch_c_mcp_new_beginnings = { "Only the {C:attention}Jokers{} from a fresh save appear" },
            ch_c_mcp_no_commons     = { "{C:attention}Common{} Jokers cannot appear" },
            ch_c_mcp_ancient_tech   = { "No {C:planet}Planet{} cards, packs or tags" },
            ch_c_mcp_stargazer      = { "No {C:tarot}Tarot{} cards, packs or tags" },
            ch_c_mcp_recovered      = { "Start with only {C:attention}face cards{}. Hand size is {C:attention}5{}" },
            ch_c_mcp_baby           = { "{C:attention}Jokers{} only add {C:chips}Chips{}, {C:mult}Mult{} and {C:money}money{}" },
            ch_c_mcp_baby_jokers    = { "No {C:attention}XMult{}, retriggers, copying or destruction" },
            ch_c_mcp_baby_bosses    = { "Boss Blinds have no ability. Blinds cannot be skipped" },
            ch_c_mcp_baby_scaling   = { "Blind sizes are about {C:attention}25%{} of normal" },
        },
    },
}
